#server:
#  port: 5555

spring:
  application:
    name: edge-service
  cloud:
    gateway:
#      routes:
#        - id: service-one
#          uri: lb://service-one
#          predicates:
#            - Path=/first/**
#          filters:
#            - RewritePath=/service-one/(?<path>.*), /$\{path}
#
#        - id: service-two
#          uri: lb://service-two
#          predicates:
#            - Path=/second/**
#          filters:
#            - RewritePath=/service-one/(?<path>.*), /$\{path}
    default-filters:
#      - TokenRelay=keycloak
#      - saveSession
#  security:
#    oauth2:
#      client:
#        registration:
#          keycloak:
#            client-id: edge-service
#            client-secret: polar-keycloak-secret
#            authorization-grant-type: client_credentials
#            provider: keycloak
#            client-name: edge-service
#            scope: openid
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:4000/realms/myRealm

server:
  servlet:
    session:
      timeout: 1m  # Set session timeout to 30 minutes
  port: 5555
#
#logging:
#  level:
#    org.springframework.security: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://192.168.59.104:30012/eureka
